/**
 * This file is generated by the odata-ts-generator
 * For issues or feature request, visit the repo: https://github.com/ikemtz/OData-TS-Generator
 * Do not edit.
 */

export interface IGrossEarning {
    amount?: number;
    createdBy?: string;
    createdOnUtc?: Date;
    earningCode?: string;
    employeeId?: string;
    employeeName?: string;
    employeeNumber?: string;
    hours?: number;
    id?: string;
    jobCode?: string;
    jobOrderId?: string;
    lineOfBusiness?: string;
    payrollRefId?: string;
    processDate?: Date;
    siteId?: string;
    siteNumber?: string;
    updatedBy?: string;
    updatedOnUtc?: Date;
}

export enum GrossEarningProperties {
    AMOUNT_FIELD_NAME = 'amount',
    CREATED_BY_FIELD_NAME = 'createdBy',
    CREATED_ON_UTC_FIELD_NAME = 'createdOnUtc',
    EARNING_CODE_FIELD_NAME = 'earningCode',
    EMPLOYEE_ID_FIELD_NAME = 'employeeId',
    EMPLOYEE_NAME_FIELD_NAME = 'employeeName',
    EMPLOYEE_NUMBER_FIELD_NAME = 'employeeNumber',
    HOURS_FIELD_NAME = 'hours',
    ID_FIELD_NAME = 'id',
    JOB_CODE_FIELD_NAME = 'jobCode',
    JOB_ORDER_ID_FIELD_NAME = 'jobOrderId',
    LINE_OF_BUSINESS_FIELD_NAME = 'lineOfBusiness',
    PAYROLL_REF_ID_FIELD_NAME = 'payrollRefId',
    PROCESS_DATE_FIELD_NAME = 'processDate',
    SITE_ID_FIELD_NAME = 'siteId',
    SITE_NUMBER_FIELD_NAME = 'siteNumber',
    UPDATED_BY_FIELD_NAME = 'updatedBy',
    UPDATED_ON_UTC_FIELD_NAME = 'updatedOnUtc',
}
