/**
 * This file is generated by the odata-ts-generator
 * For issues or feature request, visit the repo: https://github.com/ikemtz/OData-TS-Generator
 * Do not edit.
 */
import { ITimeSheet } from './time-sheet.model';

export interface ITimeSheetEntry {
    clockInUtc?: Date;
    clockOutUtc?: Date;
    createdBy?: string;
    createdOnUtc?: Date;
    id?: string;
    jobCode?: string;
    jobOrderId?: string;
    siteId?: string;
    siteName?: string;
    siteNumber?: string;
    timeSheet?: ITimeSheet;
    timeSheetId?: string;
    totalElapsedHours?: number;
    updatedBy?: string;
    updatedOnUtc?: Date;
}

export enum TimeSheetEntryProperties {
    CLOCK_IN_UTC_FIELD_NAME = 'clockInUtc',
    CLOCK_OUT_UTC_FIELD_NAME = 'clockOutUtc',
    CREATED_BY_FIELD_NAME = 'createdBy',
    CREATED_ON_UTC_FIELD_NAME = 'createdOnUtc',
    ID_FIELD_NAME = 'id',
    JOB_CODE_FIELD_NAME = 'jobCode',
    JOB_ORDER_ID_FIELD_NAME = 'jobOrderId',
    SITE_ID_FIELD_NAME = 'siteId',
    SITE_NAME_FIELD_NAME = 'siteName',
    SITE_NUMBER_FIELD_NAME = 'siteNumber',
    TIME_SHEET_FIELD_NAME = 'timeSheet',
    TIME_SHEET_ID_FIELD_NAME = 'timeSheetId',
    TOTAL_ELAPSED_HOURS_FIELD_NAME = 'totalElapsedHours',
    UPDATED_BY_FIELD_NAME = 'updatedBy',
    UPDATED_ON_UTC_FIELD_NAME = 'updatedOnUtc',
}
