/**
 * This file is generated by the odata-ts-generator
 * For issues or feature request, visit the repo: https://github.com/ikemtz/OData-TS-Generator
 * Do not edit.
 */
 // tslint:disable: array-type
 
import { IGrossEarning } from './gross-earning.model';
import { ITimeSheetEntry } from './time-sheet-entry.model';

export interface ITimeSheet {
    createdBy?: string;
    createdOnUtc?: Date;
    employeeId?: string;
    employeeName?: string;
    employeeNumber?: string;
    grossEarning?: IGrossEarning;
    grossEarningId?: string;
    id?: string;
    payableHours?: number;
    timeSheetEntries?: Array<ITimeSheetEntry>;
    updatedBy?: string;
    updatedOnUtc?: Date;
    weekStartDate?: Date;
}

export enum TimeSheetProperties {
    CREATED_BY_FIELD_NAME = 'createdBy',
    CREATED_ON_UTC_FIELD_NAME = 'createdOnUtc',
    EMPLOYEE_ID_FIELD_NAME = 'employeeId',
    EMPLOYEE_NAME_FIELD_NAME = 'employeeName',
    EMPLOYEE_NUMBER_FIELD_NAME = 'employeeNumber',
    GROSS_EARNING_FIELD_NAME = 'grossEarning',
    GROSS_EARNING_ID_FIELD_NAME = 'grossEarningId',
    ID_FIELD_NAME = 'id',
    PAYABLE_HOURS_FIELD_NAME = 'payableHours',
    TIME_SHEET_ENTRIES_FIELD_NAME = 'timeSheetEntries',
    UPDATED_BY_FIELD_NAME = 'updatedBy',
    UPDATED_ON_UTC_FIELD_NAME = 'updatedOnUtc',
    WEEK_START_DATE_FIELD_NAME = 'weekStartDate',
}
